[package]
name = "rusty_tree"
version = "0.1.0"
authors = [ "Greg Cowan <cowang4@yahoo.com>" ]
edition = "2018"

[dependencies]
ansi_term = "0.12"
docopt = "1"
lazy_static = "1.4"
lscolors = "0.6"
serde = "1.0"
serde_derive = "1.0"
