[package]
name = "rusty_tree"
version = "0.1.0"
authors = [ "Greg Cowan <cowang4@yahoo.com>" ]
edition = "2018"

[dependencies]
ansi_term = "0.11"
docopt = "1"
lazy_static = "1.3"
lscolors = "0.5"
serde = "1.0"
serde_derive = "1.0"
